### ISSUE TITLE
Uncaught Error: destroyTooltip is no longer available. Please dispose the object returnedfrom  `atom.tooltips.add` instead.See the docs at https://atom.io/docs/api/latest/TooltipManager#instance-add

### ISSUE THREAD

**Issue by exalted** [gangstead/atom-incremental-search#33]
[Enter steps to reproduce below:]

1. Hit `Cmd-i`
2. Type something
3. Hit `enter`

**Atom Version**: 0.204.0
**System**: Mac OS X 10.10.3
**Thrown From**: [incremental-search](https://github.com/gangstead/atom-incremental-search) package, v4.4.0

### Stack Trace

Uncaught Error: destroyTooltip is no longer available. Please dispose the object returned
from  `atom.tooltips.add` instead.
See the docs at https://atom.io/docs/api/latest/TooltipManager#instance-add

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:615

Error: destroyTooltip is no longer available. Please dispose the object returned
from  `atom.tooltips.add` instead.
See the docs at https://atom.io/docs/api/latest/TooltipManager#instance-add
  at [object Object].$.fn.destroyTooltip.$.fn.hideTooltip (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:615:11)
  at InputView.module.exports.InputView.hideAllTooltips (/Users/exalted/.atom/packages/incremental-search/lib/input-view.coffee:61:24)
  at InputView.module.exports.InputView.detach (/Users/exalted/.atom/packages/incremental-search/lib/input-view.coffee:90:6)
  at InputView.module.exports.InputView.stopSearch (/Users/exalted/.atom/packages/incremental-search/lib/input-view.coffee:135:6)
  at space-pen-div.<anonymous> (/Users/exalted/.atom/packages/incremental-search/lib/input-view.coffee:31:50)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:178:20)

```

### Commands

```
     -0:30.7.0 core:move-down (atom-text-editor.editor.cursor-block.cursor-line-fix.is-focused)
     -0:30.4.0 editor:newline (atom-text-editor.editor.cursor-block.cursor-line-fix.is-focused)
     -0:28.8.0 core:move-to-bottom (atom-text-editor.editor.cursor-block.cursor-line-fix.is-focused)
  2x -0:28.2.0 pane:show-next-item (atom-text-editor.editor.cursor-block.cursor-line-fix.is-focused)
     -0:12.5.0 core:move-to-top (atom-text-editor.editor.cursor-block.cursor-line-fix.is-focused)
     -0:12.2.0 incremental-search:forward (atom-text-editor.editor.cursor-block.cursor-line-fix.is-focused)
  2x -0:10.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
 16x -0:08.9.0 incremental-search:forward (atom-text-editor.editor.mini.is-focused)
     -0:05.4.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:05.4.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:04.9.0 editor:move-to-first-character-of-line (atom-text-editor.editor.mini.is-focused)
     -0:04.9.0 core:move-to-top (atom-text-editor.editor.mini.is-focused)
     -0:03.9.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:03.9.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:03.0 incremental-search:forward (atom-text-editor.editor.mini.is-focused)
     -0:02.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "disabledPackages": [
      "markdown-format",
      "syntax-settings",
      "autocomplete",
      "deprecation-cop",
      "autocomplete-paths",
      "archive-view",
      "background-tips",
      "bookmarks",
      "image-view"
    ],
    "projectHome": "/Users/exalted/Development",
    "followSymlinks": true,
    "themes": [
      "atom-light-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-emojis, v2.2.2
block-cursor, v0.12.5
highlight-selected, v0.9.3
incremental-search, v4.4.0
language-csharp, v0.5.0
linter, v0.12.6
linter-coffeelint, v0.2.4
linter-erb, v0.1.1
linter-jshint, v0.1.5
linter-rubocop, v0.2.7
linter-shellcheck, v0.0.8
linter-tidy, v1.0.1

# Dev
No dev packages
```

**Comment by gangstead** [comment]
Known issue. It'll be fixed as part of upgrading the deprecated libraries by the 6/1/15 cutoff... hopefully.

**Comment by exalted** [comment]
:beers:

**Comment by gangstead** [comment]
Please give `v5.0.1` a try.  It's not perfect, slurping still seems to be broken (it looks like core atom find-and-replace stole the hot key), but I can arbitrarily open, close incremental search, type out queries while it advances, advance to the next match, add to query with everything working as expected and no uncaught errors popping up.
