### ISSUE TITLE
Failed to activate the incremental-search package

### ISSUE THREAD

**Issue by rpietro** [gangstead/atom-incremental-search#40]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [incremental-search](https://github.com/gangstead/atom-incremental-search) package, v5.0.1

### Stack Trace

Failed to activate the incremental-search package

```
At Cannot find module 'atom-space-pen-views'

Error: Cannot find module 'atom-space-pen-views'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/Users/rpietro/.atom/packages/atom-incremental-search/lib/isearch.coffee:4:7)
    at Object.<anonymous> (/Users/rpietro/.atom/packages/atom-incremental-search/lib/isearch.coffee:65:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
```

### Commands

```
     -0:00.5.0 incremental-search:forward (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
language-todotxt, v0.6.1

# Dev
No dev packages
```

**Comment by gangstead** [comment]
Not sure what to do about this one.  Looks like Atom didn't npm install the dependency.  Can't fix that from here.
