### ISSUE TITLE
Uncaught TypeError: this.editSession.getBuffer(...).off is not a function

### ISSUE THREAD

**Issue by vmalloc** [gangstead/atom-incremental-search#45]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11.1
**Thrown From**: [incremental-search](https://github.com/gangstead/atom-incremental-search) package, v5.0.1

### Stack Trace

Uncaught TypeError: this.editSession.getBuffer(...).off is not a function

```
At /Users/rotemy/.atom/packages/incremental-search/lib/search-model.coffee:168

TypeError: this.editSession.getBuffer(...).off is not a function
  at SearchModel.module.exports.SearchModel.cleanup (/Users/rotemy/.atom/packages/incremental-search/lib/search-model.coffee:168:32)
  at SearchModel.module.exports.SearchModel.cancelSearch (/Users/rotemy/.atom/packages/incremental-search/lib/search-model.coffee:151:6)
  at InputView.module.exports.InputView.cancelSearch (/Users/rotemy/.atom/packages/incremental-search/lib/input-view.coffee:147:18)
  at space-pen-div.subscriptions.add.atom.commands.add.core:cancel (/Users/rotemy/.atom/packages/incremental-search/lib/input-view.coffee:37:26)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:184:20)

```

### Commands

```
     -0:09.4.0 incremental-search:forward (atom-text-editor.editor.is-focused)
     -0:06.4.0 editor:delete-to-beginning-of-word (atom-text-editor.editor.mini.is-focused)
     -0:03.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:02.4.0 core:move-right (atom-text-editor.editor.mini.is-focused)
     -0:02.2.0 core:move-left (atom-text-editor.editor.mini.is-focused)
     -0:01.3.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:01.3.0 core:cancel (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "openEmptyEditorOnStart": false
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v2.0.13
emmet, v2.3.13
file-icons, v1.6.11
incremental-search, v5.0.1
linter, v1.9.0
linter-jshint, v1.2.1
linter-pylint, v1.0.3

# Dev
No dev packages
```

**Comment by eltechnic0** [comment]
Same error here.

**Comment by DenisPostu** [comment]
[Enter steps to reproduce below:]

1. `CTRL+i` to get incremental search panel open
2. type some character into the text field
3. hit `ESC`

**Atom Version**: 1.4.0-beta0
**System**: Microsoft Windows 10 Enterprise
**Thrown From**: [incremental-search](https://github.com/gangstead/atom-incremental-search) package, v5.0.1


### Stack Trace

Uncaught TypeError: this.editSession.getBuffer(...).off is not a function

```
At /C:/Users/depostu/.atom/packages/incremental-search/lib/search-model.coffee:160

TypeError: this.editSession.getBuffer(...).off is not a function
    at SearchModel.module.exports.SearchModel.cleanup (file:///C:/Users/depostu/.atom/packages/incremental-search/lib/search-model.coffee:168:32)
    at SearchModel.module.exports.SearchModel.cancelSearch (file:///C:/Users/depostu/.atom/packages/incremental-search/lib/search-model.coffee:151:6)
    at InputView.module.exports.InputView.cancelSearch (file:///C:/Users/depostu/.atom/packages/incremental-search/lib/input-view.coffee:147:18)
    at space-pen-div.subscriptions.add.atom.commands.add.core:cancel (file:///C:/Users/depostu/.atom/packages/incremental-search/lib/input-view.coffee:37:26)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\depostu\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\depostu\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\depostu\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\depostu\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (C:\Users\depostu\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (C:\Users\depostu\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\window-event-handler.js:3:61)
```

### Commands

```
     -2:39.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -1:22.8.0 core:close (atom-text-editor.editor.is-focused)
     -0:57.9.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:55.5.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -0:53.4.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:53.4.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:50.3.0 incremental-search:forward (atom-text-editor.editor.is-focused)
  3x -0:45.9.0 find-and-replace:find-next (atom-text-editor.editor.mini.is-focused)
  3x -0:43.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:41.8.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:41.8.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:37.5.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:37.5.0 core:cancel (atom-text-editor.editor.mini.is-focused)
  2x -0:03.1.0 incremental-search:forward (atom-text-editor.editor.is-focused)
     -0:01.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:01.0 core:cancel (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "open-on-github",
      "terminal-plus"
    ],
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
incremental-search, v5.0.1
language-typescript-grammars-only, v1.3.0
minimap, v4.18.0
pretty-json, v0.4.1
project-manager, v2.6.5
terminal-panel, v1.14.1

# Dev
No dev packages
```

**Comment by kumarharsh** [comment]
+1 happening here too

**Comment by kumarharsh** [comment]
Looking at the activity, is this project dead? There are so many issues, all basically screaming that this plugin does not work anymore.

**Comment by kumarharsh** [comment]
Going with `isearch`. Less features, but atleast it works

**Comment by danielhq** [comment]
Same happening with me.

Any solutions?

**Comment by kumarharsh** [comment]
Use `isearch`. That's all I can say. It doesn't have regex support right now, but it works very well (in fact better than sublime in showing matches)

**Comment by gangstead** [comment]
Yeah I'm trying to get this package up to date again, I need more help. I wish they would just put incremental search into the default find-and-replace.

**Comment by gangstead** [comment]
Looks to be a common problem with a lot of packages lately: https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=atom%20pane%20getbuffer

I'll see if I can figure out how other people are getting the buffer if it's no longer available from the pane.

**Comment by gangstead** [comment]
Please update to `v5.0.3`
