### ISSUE TITLE
Uncaught TypeError: this.editSession.getCursor is not a function

### ISSUE THREAD

**Issue by perseghini** [gangstead/atom-incremental-search#46]
[Enter steps to reproduce below:]

1. cmd-i to start incremental search.
2. search anything existing in the current file
3. cmd-e

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11
**Thrown From**: [incremental-search](https://github.com/gangstead/atom-incremental-search) package, v5.0.1

### Stack Trace

Uncaught TypeError: this.editSession.getCursor is not a function

```
At /Users/perseghini/.atom/packages/incremental-search/lib/search-model.coffee:113

TypeError: this.editSession.getCursor is not a function
  at SearchModel.module.exports.SearchModel.slurp (/Users/perseghini/.atom/packages/incremental-search/lib/search-model.coffee:113:27)
  at InputView.module.exports.InputView.slurp (/Users/perseghini/.atom/packages/incremental-search/lib/input-view.coffee:70:18)
  at space-pen-div.subscriptions.add.atom.commands.add.incremental-search:slurp (/Users/perseghini/.atom/packages/incremental-search/lib/input-view.coffee:41:39)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:184:20)

```

### Commands

```
     -0:31.3.0 find-and-replace:use-selection-as-find-pattern (atom-text-editor.editor.is-focused)
     -0:28.2.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:28.2.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:26.2.0 find-and-replace:use-selection-as-find-pattern (atom-text-editor.editor.is-focused)
     -0:23 core:move-right (atom-text-editor.editor.mini.is-focused)
  2x -0:22.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -0:19.4.0 find-and-replace:find-next (atom-text-editor.editor.mini.is-focused)
  4x -0:17.8.0 core:move-up (atom-text-editor.editor.is-focused)
  3x -0:16.6.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:15.9.0 find-and-replace:use-selection-as-find-pattern (atom-text-editor.editor.is-focused)
 26x -0:13.7.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:09.4.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:09.4.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:08.6.0 incremental-search:forward (atom-text-editor.editor.is-focused)
 10x -0:07.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:01.4.0 incremental-search:slurp (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ],
    "disabledPackages": [
      "linter-pep257",
      "vim-mode"
    ],
    "packagesWithKeymapsDisabled": []
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.15
atom-material-syntax, v0.2.4
atom-material-ui, v0.6.2
autocomplete-python, v0.8.2
clipboard-history, v0.6.6
color-picker, v2.0.13
file-icons, v1.6.11
git-log, v0.4.1
highlight-selected, v0.10.1
incremental-search, v5.0.1
last-cursor-position, v0.9.0
linter, v1.9.1
linter-flake8, v1.9.1
pigments, v0.18.0
wakatime, v5.0.0
white-cursor, v0.6.0

# Dev
No dev packages
```

**Comment by gangstead** [comment]
I haven't got slurping working again since I took over the package from the original author.  Hopefully someone can help out on it.

**Comment by gangstead** [comment]
Created a help wanted ticket #49

**Comment by gangstead** [comment]
Please update to `v.5.0.4` and verify that it's fixed.
